name: Deploy to Local Windows Server

on:
  push:
    branches:
      - main  # Trigger khi code được push lên nhánh main

jobs:
  deploy:
    runs-on: self-hosted  # Chạy trực tiếp trên máy chủ Windows cục bộ của bạn
    
    steps:
      - name: Pull Latest Code and Deploy
        shell: cmd
        run: |
          d:
          cd D:\GhepKhoa
          git fetch --all
          git reset --hard origin/main
          cd web
          npm install
          npm run build
          pm2 restart GhepKhoa
